//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidTireEstimates.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estimate()
        {
            this.EstimateComments = new HashSet<EstimateComment>();
            this.ServiceEstimates = new HashSet<ServiceEstimate>();
            this.ShopParts = new HashSet<ShopPart>();
            this.VehicleParts = new HashSet<VehiclePart>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public string FinalPrice { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimateComment> EstimateComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceEstimate> ServiceEstimates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopPart> ShopParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiclePart> VehicleParts { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
