//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidTireEstimates.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RapidTireEstimatesdbEntities : DbContext
    {
        public RapidTireEstimatesdbEntities()
            : base("name=RapidTireEstimatesdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Estimate> Estimates { get; set; }
        public virtual DbSet<ServiceEstimate> ServiceEstimates { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
