//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidTireEstimates.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePrice : Price
    {
        public string Description { get; set; }
        public short Level { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
