//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidTireEstimates.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceEstimate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceEstimate()
        {
            this.ServiceEstimateComments = new HashSet<ServiceEstimateComment>();
        }
    
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int EstimateId { get; set; }
    
        public virtual EstimatePrice EstimatePrice { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceEstimateComment> ServiceEstimateComments { get; set; }
        public virtual Estimate Estimate { get; set; }
    }
}
